version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: ticket_system_db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: ticket_system
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    
    command: --init-file /docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: